version: '3.1'

services:
  db:
    platform: linux/x86_64
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env.local
    environment:
      MYSQL_ROOT_PASSWORD: 111111
      MYSQL_DATABASE: local
    ports:
      - 3306:3306
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
